repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.0
    hooks:
    - id: ruff
      args: [ --fix ]
    - id: ruff-format
  - repo: local
    hooks:
    - id: mypy
      name: mypy
      language: system
      entry: "mypy"
      types: [python]
      require_serial: true


files: ^agentic_radar/
