name: Generate PR Screenshots

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'agentic_radar/report/templates/**'
      - 'agentic_radar/report/graph/**'
      - 'agentic_radar/cli.py'
      - 'agentic_radar/report/report.py'

jobs:
  generate-screenshots:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install pytest playwright
        playwright install chromium
    
    - name: Generate screenshots
      run: |
        mkdir -p pr-screenshots
        python -m pytest tests/test_visual_ux_capture.py::TestVisualUXCapture::test_capture_full_report_screenshot -v -s --tb=short || true
        python -m pytest tests/test_visual_ux_capture.py::TestVisualUXCapture::test_capture_graph_only_screenshot -v -s --tb=short || true
        python -m pytest tests/test_visual_ux_capture.py::TestVisualUXCapture::test_capture_vis_js_vs_force_graph_comparison -v -s --tb=short || true
        
        # Move screenshots to PR directory
        find /tmp -name "*screenshot*.png" -exec cp {} pr-screenshots/ \; 2>/dev/null || true
        ls -la pr-screenshots/
    
    - name: Upload screenshots as artifacts
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: pr-screenshots-${{ github.event.number }}
        path: pr-screenshots/
        retention-days: 30
    
    - name: Comment on PR with screenshots
      if: always()
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs');
          const path = require('path');
          
          // Check if screenshots directory exists and has files
          const screenshotsDir = 'pr-screenshots';
          let screenshotFiles = [];
          
          try {
            screenshotFiles = fs.readdirSync(screenshotsDir).filter(file => file.endsWith('.png'));
          } catch (error) {
            console.log('No screenshots directory found');
            return;
          }
          
          if (screenshotFiles.length === 0) {
            console.log('No screenshots generated');
            return;
          }
          
          const artifactUrl = `https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}`;
          
          let comment = `## 📸 Visual Changes Preview\n\n`;
          comment += `Screenshots have been generated to show the visual impact of these changes.\n\n`;
          comment += `**Generated Screenshots:**\n`;
          
          screenshotFiles.forEach(file => {
            const name = file.replace('.png', '').replace(/_/g, ' ');
            comment += `- ${name}\n`;
          });
          
          comment += `\n**Download Screenshots:** [View Artifacts](${artifactUrl})\n\n`;
          comment += `> 🤖 Screenshots automatically generated by GitHub Actions\n`;
          comment += `> These show the actual rendered UI to help review visual changes.`;
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });