on:
  push:
    branches:
      - main

name: release-please

permissions:
  contents: write
  pull-requests: write
  id-token: write

env:
  POETRY_VERSION: 2.0.1

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: python

      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}
      - uses: actions/setup-python@v5
        if: ${{ steps.release.outputs.release_created }}
        with:
          python-version: '3.11'

      - name: Install poetry
        if: ${{ steps.release.outputs.release_created }}
        run: curl -sSL https://install.python-poetry.org | python3 - --version $POETRY_VERSION

      - name: Install dependencies
        if: ${{ steps.release.outputs.release_created }}
        run: | 
          poetry install --all-extras

      - name: Run tests
        if: ${{ steps.release.outputs.release_created }}
        run: |
          poetry run python -m pytest -v -s

      - name: Run checks
        if: ${{ steps.release.outputs.release_created }}
        run: | 
          poetry run ruff check
          poetry run mypy agentic_radar
        
      - name: Build
        if: ${{ steps.release.outputs.release_created }}
        run: poetry build

      - name: Publish pypi
        if: ${{ steps.release.outputs.release_created }}
        uses: pypa/gh-action-pypi-publish@release/v1
